/**
 * TEAM MODEL  (models/team.model.js)
 * ====================================
 * The Model is the "M" in MVC. It is the only layer that directly reads from
 * and writes to the data store (in this case, a JSON file via DbService).
 *
 * RESPONSIBILITIES OF A MODEL
 * ----------------------------
 * 1. Abstract all data persistence behind clean, semantic method names
 *    (getAll, getById, create) so callers never deal with raw file I/O.
 * 2. Define the structure (shape) of a data record.
 * 3. Enforce data-integrity rules that are specific to the data store
 *    (e.g. no duplicate team names).
 * 4. Generate new record identifiers (UUIDs) before insertion.
 *
 * WHAT A MODEL MUST NOT DO
 * -------------------------
 * - It must NOT know about HTTP (no req, res, status codes).
 * - It must NOT contain business logic such as computing league standings.
 *   That belongs in the Service layer.
 *
 * PRIVATE FIELDS AND METHODS (#)
 * --------------------------------
 * The `#db`, `#read()` and `#write()` members use the ES2022 private class
 * field syntax. The leading `#` makes them inaccessible outside the class,
 * enforcing encapsulation: callers can only interact through the public API
 * (getAll, getById, create).
 */

import { randomUUID } from 'crypto';
import { DbService } from '../services/db.service.js';

export class TeamModel {
	/**
	 * Private instance of DbService bound to "teams.json".
	 * All reads and writes go through this single object, keeping file-path
	 * concerns entirely inside this class.
	 */
	#db = new DbService('teams.json');

	/**
	 * Private helper — reads the entire teams array from the JSON file.
	 * Wrapping db.read() here means future storage changes (e.g. switching
	 * to a real database) only require editing this one private method.
	 */
	#read() {
		return this.#db.read();
	}

	/**
	 * Private helper — persists the entire teams array back to the JSON file.
	 * The full array is always written (as opposed to partial updates) because
	 * the JSON file is treated as a simple flat list.
	 */
	#write(teams) {
		return this.#db.write(teams);
	}

	/**
	 * Returns every team record in the database.
	 * Thin delegation to #read() — no filtering or transformation.
	 */
	getAll() {
		return this.#read();
	}

	/**
	 * Finds and returns a single team by its UUID.
	 * Returns null (not an error) when no match is found — following the
	 * convention that "not found" is an expected outcome at the data layer.
	 * The Service layer is responsible for deciding whether null is an error.
	 */
	async getById(id) {
		const teams = await this.#read();

		const team = teams.find(team => team.id === id);

		// Nullish coalescing: return the found team or null (never undefined).
		return team ?? null;
	}

	/**
	 * Creates and persists a new team record.
	 *
	 * DATA INTEGRITY RULE: duplicate team names are rejected at this layer
	 * because it is a constraint of the data store, not a business rule.
	 * Case-insensitive comparison prevents "arsenal" vs "Arsenal" duplicates.
	 *
	 * DEFAULT VALUES:
	 * - id       → UUID v4 generated by Node's built-in crypto module.
	 * - stadium  → "Unknown Stadium" when not provided.
	 * - founded  → null when not provided.
	 * - All match stats (wins, draws, losses, goals) start at 0 for a new team.
	 *
	 * The write is intentionally NOT awaited in a separate step — push() and
	 * write() happen within the same function to keep the data consistent.
	 */
	async create({ name, country, stadium, founded }) {
		const teams = await this.#read();

		const isExists = teams.some(
			team => team.name.toLowerCase() === name.toLowerCase(),
		);

		if (isExists) {
			throw new Error(`Team with name: ${name} already exists.`);
		}

		const team = {
			id: randomUUID(),
			name,
			country,
			stadium: stadium || 'Unknown Stadium',
			founded: founded || null,
			wins: 0,
			draws: 0,
			losses: 0,
			goalsFor: 0,
			goalsAgainst: 0,
		};

		teams.push(team);
		this.#write(teams);

		return team;
	}
}

// Export a single shared instance — the model is stateless (all state lives
// in the JSON file), so one instance is shared across the application.
export const Team = new TeamModel();
